spring.application.name=accounting-service

# ===============================
# Kafka Consumer Group - Accounting Service
# ===============================
spring.kafka.consumer.group-id=accounting-service-group

