
# ==============================================================
# HR SERVICE CONFIGURATION
# ==============================================================

spring.application.name=hr-service
server.port=8080

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-nameless-flower-ahqfkw3x-pooler.c-3.us-east-1.aws.neon.tech/hr_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ODZx4pvMKCU1

# ===============================
# Kafka Consumer Group - HR Service
# ===============================
spring.kafka.consumer.group-id=hr-service-group

# ===============================
# Actuator Configuration
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.enabled=true
management.metrics.enable.jvm=true
management.metrics.enable.http.server.requests=true
management.server.port=8080
management.metrics.tags.application=${spring.application.name}


