
spring.application.name=hr-service
server.port=8080

# ===============================
# Kafka Consumer Group - HR Service
# ===============================
spring.kafka.consumer.group-id=hr-service-group

# ===============================
# Actuator Configuration
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.enabled=true
management.metrics.enable.jvm=true
management.metrics.enable.http.server.requests=true
management.server.port=8080
management.metrics.tags.application=${spring.application.name}


