spring.application.name=inventory-service

# ===============================
# Kafka Consumer Group - Inventory Service
# ===============================
spring.kafka.consumer.group-id=inventory-service-group

