
spring.application.name=log-ingest-service
server.port=8080

# ===============================
# Kafka Consumer Group - Log Ingest Service
# ===============================
spring.kafka.consumer.group-id=log-ingest-service-group


