
# ==============================================================
# LOG INGEST SERVICE CONFIGURATION
# ==============================================================

spring.application.name=log-ingest-service
server.port=8080

# ===============================
# MongoDB Configuration
# ===============================
spring.mongodb.uri=mongodb+srv://2224802010076_db_user:Atlas2224802010076@test0.mzf1z5y.mongodb.net/logging_db?retryWrites=true&w=majority
spring.mongodb.database=logging_db

# ===============================
# Kafka Consumer Group - Log Ingest Service
# ===============================
spring.kafka.consumer.group-id=log-ingest-service-group


