
spring.application.name=organization-service
server.port=8080

# ===============================
# Kafka Consumer Group - Organization Service
# ===============================
spring.kafka.consumer.group-id=organization-service-group

# ===============================
# Actuator Configuration
# ===============================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never


