
# ==============================================================
# ORGANIZATION SERVICE CONFIGURATION
# ==============================================================

spring.application.name=organization-service
server.port=8080

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-nameless-flower-ahqfkw3x-pooler.c-3.us-east-1.aws.neon.tech/organization_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ODZx4pvMKCU1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Kafka Consumer Group - Organization Service
# ===============================
spring.kafka.consumer.group-id=organization-service-group

# ===============================
# Actuator Configuration
# ===============================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never


