spring.application.name=payroll-service

# ===============================
# Kafka Consumer Group - Payroll Service
# ===============================
spring.kafka.consumer.group-id=payroll-service-group

