# ==============================================================
# PAYROLL SERVICE CONFIGURATION
# ==============================================================

spring.application.name=payroll-service

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-nameless-flower-ahqfkw3x-pooler.c-3.us-east-1.aws.neon.tech/payroll_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ODZx4pvMKCU1

# ===============================
# Kafka Consumer Group - Payroll Service
# ===============================
spring.kafka.consumer.group-id=payroll-service-group

