spring.application.name=production-service

# ===============================
# Kafka Consumer Group - Production Service
# ===============================
spring.kafka.consumer.group-id=production-service-group

