spring.application.name=reporting-service

# ===============================
# Kafka Consumer Group - Reporting Service
# ===============================
spring.kafka.consumer.group-id=reporting-service-group

