
spring.application.name=workflow-service
server.port=8080

# ===============================
# Kafka Consumer Group - Workflow Service
# ===============================
spring.kafka.consumer.group-id=workflow-service-group


